version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - mailpit

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ovasafe
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025" # UI Mailpit
      - "1025:1025" # SMTP port

volumes:
  mysql_data:
